/**
 * Firebase test helpers.
 *
 * These helpers provide utilities for working with Firebase in e2e tests.
 * Note: For true isolation, consider using Firebase emulators.
 */

/**
 * Generate a unique test player name.
 */
export function generateTestPlayerName(prefix = 'TestPlayer'): string {
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).substring(2, 6);
  return `${prefix}_${timestamp}_${random}`;
}

/**
 * Generate a unique test room code.
 * Note: This is for reference only - actual room codes are generated by the app.
 */
export function generateTestRoomCode(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  let code = '';
  for (let i = 0; i < 6; i++) {
    code += chars[Math.floor(Math.random() * chars.length)];
  }
  return code;
}

/**
 * Wait for Firebase sync to complete.
 * This is a simple delay-based approach - for more robust testing,
 * consider using Firebase emulators with direct database access.
 */
export async function waitForFirebaseSync(ms = 1000): Promise<void> {
  await new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Test data generators.
 */
export const testData = {
  /**
   * Generate player data.
   */
  player(overrides: Partial<{ name: string; isHost: boolean }> = {}) {
    return {
      name: generateTestPlayerName(),
      isHost: false,
      ...overrides,
    };
  },

  /**
   * Generate game settings.
   */
  gameSettings(overrides: Partial<{ duration: number; gridSize: number }> = {}) {
    return {
      duration: 60, // Short duration for tests
      gridSize: 5,
      ...overrides,
    };
  },
};

/**
 * Known valid words for testing word submission.
 * These are common 3-4 letter words likely to appear in grids.
 */
export const testWords = {
  // Common 3-letter words
  short: ['THE', 'AND', 'FOR', 'ARE', 'BUT', 'NOT', 'YOU', 'ALL', 'CAN', 'HAD'],

  // Common 4-letter words
  medium: ['THAT', 'WITH', 'HAVE', 'THIS', 'WILL', 'YOUR', 'FROM', 'THEY', 'BEEN', 'SOME'],

  // Words that are definitely NOT valid
  invalid: ['XYZ', 'QQQ', 'ZZZ', 'AAA', 'ASDF', 'QWERTY'],
};

/**
 * Environment configuration for tests.
 */
export const testConfig = {
  /**
   * Short timeout for fast tests.
   */
  shortTimeout: 5000,

  /**
   * Medium timeout for normal tests.
   */
  mediumTimeout: 15000,

  /**
   * Long timeout for slow operations.
   */
  longTimeout: 30000,

  /**
   * Game duration for tests (shorter than default).
   */
  testGameDuration: 30,
};
